# Generated by Cloud66 Starter
FROM ruby:2.3.3

RUN apt-get update -qq && apt-get install -y build-essential 

ENV APP_HOME /app

RUN mkdir $APP_HOME
WORKDIR $APP_HOME

ADD Gemfile* $APP_HOME/
RUN gem install bundler && bundle config --global silence_root_warning 1
RUN bundle install --jobs 20 --retry 5

ADD . $APP_HOME

